name: hilbert-lab
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - spacy
  - networkx
  - matplotlib
  - graphviz
  - python-graphviz
  - tqdm
  - fastapi
  - uvicorn
  - cmake
  - ninja
  - pybind11
  - pytest
  - flake8
  - black
  - mypy
  - pip:
      []
