name: Hilbert CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: hilbert-lab
          environment-file: environment.yml
          python-version: 3.10
          auto-activate-base: false
          use-mamba: true

      - name: Verify Conda environment
        run: |
          echo "Python:" $(python --version)
          echo "Conda env:" $(conda info --envs)

      - name: Install package (PEP517)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Install linters & pytest
        run: |
          pip install flake8 pytest

      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=12 \
            --max-line-length=79 --statistics

      - name: Run tests
        run: pytest
