name: Hilbert CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: hilbert-lab
          environment-file: environment.yml
          python-version: 3.10
          use-mamba: true

      - name: Confirm environment
        run: |
          conda info
          conda list

      - name: Install package
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Install dev tools
        run: |
          pip install flake8 pytest

      - name: Run Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=12 \
            --max-line-length=88 --statistics

      - name: Run Tests
        run: pytest
